# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

jobs:
- job: WebApp
  pool:
    vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - task: DotNetCoreCLI@1
    displayName: ".NET publish package"
    condition: ${{ parameters.deployPackage }}
    inputs:
      command: publish
      arguments: --configuration ${{ parameters.buildConfiguration }} --no-restore --output $(Build.ArtifactStagingDirectory)/app/pkg

  - task: PublishBuildArtifacts@1
    displayName: "Publish artifacts"
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
      ArtifactName: app